---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: webhook
spec:
  serviceAccountName: pipeline
  triggers:
    - name: build-pipeline
      bindings:
        - ref: quay-push-repository
      template:
        ref: build-pipeline
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: el-webhook
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: webhook
spec:
  port:
    targetPort: http-listener
  to:
    kind: "Service"
    name: el-webhook
    weight: 100
