apiVersion: v1
kind: Secret
metadata:
  name: quay-auth-secret
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LTk2YTAuYXBwcy5zaGFyZWQtbmE0Lm5hNC5vcGVuc2hpZnQub3BlbnRsYy5jb20iOiB7CiAgICAgICJhdXRoIjogIlpHVnRieXRqYVRwTVIwYzNXVmc0TVRORFREQklOa3hSVHpsSE1WZE5NRXhTV2paRFIwYzVWams1V2xkTlRGWXhTRTlFVlV4R1NsSkVUVVpZVTB4T1ZGYzBTbFJZTURCWiIsCiAgICAgICJlbWFpbCI6ICIiCiAgICB9CiAgfQp9
type: kubernetes.io/dockerconfigjson